(cl:in-package autoware_config_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          AUTO_MISSION_RELOAD-VAL
          AUTO_MISSION_RELOAD
          AUTO_ENGAGE-VAL
          AUTO_ENGAGE
          AUTO_MISSION_CHANGE-VAL
          AUTO_MISSION_CHANGE
          USE_FMS-VAL
          USE_FMS
          DISUSE_VECTOR_MAP-VAL
          DISUSE_VECTOR_MAP
          NUM_OF_STEER_BEHIND-VAL
          NUM_OF_STEER_BEHIND
          CHANGE_THRESHOLD_DIST-VAL
          CHANGE_THRESHOLD_DIST
          CHANGE_THRESHOLD_ANGLE-VAL
          CHANGE_THRESHOLD_ANGLE
          GOAL_THRESHOLD_DIST-VAL
          GOAL_THRESHOLD_DIST
          GOAL_THRESHOLD_VEL-VAL
          GOAL_THRESHOLD_VEL
          STOPPED_VEL-VAL
          STOPPED_VEL
))