// Generated by gencpp from file autoware_map_msgs/LaneAttributeRelationArray.msg
// DO NOT EDIT!


#ifndef AUTOWARE_MAP_MSGS_MESSAGE_LANEATTRIBUTERELATIONARRAY_H
#define AUTOWARE_MAP_MSGS_MESSAGE_LANEATTRIBUTERELATIONARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <autoware_map_msgs/LaneAttributeRelation.h>

namespace autoware_map_msgs
{
template <class ContainerAllocator>
struct LaneAttributeRelationArray_
{
  typedef LaneAttributeRelationArray_<ContainerAllocator> Type;

  LaneAttributeRelationArray_()
    : header()
    , data()  {
    }
  LaneAttributeRelationArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::autoware_map_msgs::LaneAttributeRelation_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::autoware_map_msgs::LaneAttributeRelation_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> const> ConstPtr;

}; // struct LaneAttributeRelationArray_

typedef ::autoware_map_msgs::LaneAttributeRelationArray_<std::allocator<void> > LaneAttributeRelationArray;

typedef boost::shared_ptr< ::autoware_map_msgs::LaneAttributeRelationArray > LaneAttributeRelationArrayPtr;
typedef boost::shared_ptr< ::autoware_map_msgs::LaneAttributeRelationArray const> LaneAttributeRelationArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autoware_map_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'autoware_map_msgs': ['/home/adeye/AD-EYE_Core/autoware.ai/src/autoware/messages/autoware_map_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5de320de3a099cd884bcebcfd4c2798e";
  }

  static const char* value(const ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5de320de3a099cd8ULL;
  static const uint64_t static_value2 = 0x84bcebcfd4c2798eULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_map_msgs/LaneAttributeRelationArray";
  }

  static const char* value(const ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This consists of multiple LaneAttributeRelation objects in a map. \n\
\n\
Header header\n\
LaneAttributeRelation[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: autoware_map_msgs/LaneAttributeRelation\n\
# This describes an attribute of lane in a map.\n\
\n\
# ATTRIBUTE_TYPES\n\
uint32 PLANE = 1\n\
uint32 INTERSECTION = 2\n\
uint32 CROSS_WALK = 3\n\
uint32 DISABLE_LANE_CHANGE = 4\n\
uint32 DISABLE_PARKING = 5\n\
uint32 RAILROAD = 6\n\
uint32 PEDESTRIAN_SPACE = 7\n\
uint32 PARKING_AREA = 8\n\
\n\
# Id of Lane object which attribute is applied.\n\
int32 lane_id\n\
\n\
# Attribute that is applied to lane\n\
# Must be one of ATTRIBUTE_TYPES\n\
int32 attribute_type\n\
\n\
# Id of Area object that is relevant to the attribute (if exists). \n\
# e.g. Id of Area object that describes crosswalk when attribute_type = CROSS_WALK. \n\
int32 area_id\n\
";
  }

  static const char* value(const ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneAttributeRelationArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_map_msgs::LaneAttributeRelationArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::autoware_map_msgs::LaneAttributeRelation_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_MAP_MSGS_MESSAGE_LANEATTRIBUTERELATIONARRAY_H
