// Generated by gencpp from file autoware_map_msgs/LaneRelation.msg
// DO NOT EDIT!


#ifndef AUTOWARE_MAP_MSGS_MESSAGE_LANERELATION_H
#define AUTOWARE_MAP_MSGS_MESSAGE_LANERELATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autoware_map_msgs
{
template <class ContainerAllocator>
struct LaneRelation_
{
  typedef LaneRelation_<ContainerAllocator> Type;

  LaneRelation_()
    : lane_id(0)
    , next_lane_id(0)
    , blinker(0)  {
    }
  LaneRelation_(const ContainerAllocator& _alloc)
    : lane_id(0)
    , next_lane_id(0)
    , blinker(0)  {
  (void)_alloc;
    }



   typedef int32_t _lane_id_type;
  _lane_id_type lane_id;

   typedef int32_t _next_lane_id_type;
  _next_lane_id_type next_lane_id;

   typedef int32_t _blinker_type;
  _blinker_type blinker;



  enum {
    None = 0u,
    Left = 1u,
    Right = 2u,
  };


  typedef boost::shared_ptr< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> const> ConstPtr;

}; // struct LaneRelation_

typedef ::autoware_map_msgs::LaneRelation_<std::allocator<void> > LaneRelation;

typedef boost::shared_ptr< ::autoware_map_msgs::LaneRelation > LaneRelationPtr;
typedef boost::shared_ptr< ::autoware_map_msgs::LaneRelation const> LaneRelationConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_map_msgs::LaneRelation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autoware_map_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'autoware_map_msgs': ['/home/adeye/AD-EYE_Core/autoware.ai/src/autoware/messages/autoware_map_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3dff6505b3e88becc76b5332fcd57ed";
  }

  static const char* value(const ::autoware_map_msgs::LaneRelation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3dff6505b3e88beULL;
  static const uint64_t static_value2 = 0xcc76b5332fcd57edULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_map_msgs/LaneRelation";
  }

  static const char* value(const ::autoware_map_msgs::LaneRelation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This represents lane connections in a map.\n\
\n\
# BlinkerType\n\
uint8 None = 0\n\
uint8 Left = 1\n\
uint8 Right = 2\n\
\n\
# Id of refering Lane object.\n\
int32 lane_id\n\
\n\
# Id of Lane objects that follows after refering lane. \n\
int32 next_lane_id\n\
\n\
# Blinker that must be lit when doing driving towards the next_lane.\n\
# Must be one of \"Blinker Type\"\n\
# e.g. if next_lane_id is left turning lane in intersection, then blinker = LEFT\n\
int32 blinker\n\
";
  }

  static const char* value(const ::autoware_map_msgs::LaneRelation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lane_id);
      stream.next(m.next_lane_id);
      stream.next(m.blinker);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneRelation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_map_msgs::LaneRelation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_map_msgs::LaneRelation_<ContainerAllocator>& v)
  {
    s << indent << "lane_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lane_id);
    s << indent << "next_lane_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.next_lane_id);
    s << indent << "blinker: ";
    Printer<int32_t>::stream(s, indent + "  ", v.blinker);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_MAP_MSGS_MESSAGE_LANERELATION_H
