#!/bin/bash

REPOS="common core_perception core_planning messages utilities visualization"

HTTPS_LINK="https://github.com/AD-EYE"
SSH_LINK="git@github.com:AD-EYE"

if [[ $1 == "ssh" ]]; then
    BASE_LINK=$SSH_LINK
else
    BASE_LINK=$HTTPS_LINK
fi

# Make the directories
mkdir -p src
cd src
mkdir -p autoware
mkdir -p drivers

# Autoware folder
cd autoware

for repo_name in $REPOS
do
    git clone ${BASE_LINK}/${repo_name}.git
    cd $repo_name
    git checkout dev
    cd ..
done
