#ifndef __DBC_H__
#define __DBC_H__

#include <string>

#include "DBC/SSMBMid6CanFdFr01.h"
#include "DBC/SSMBMid6CanFdFr02.h"
#include "DBC/SSMBMid6CanFdFr03.h"
#include "DBC/SSMBMid6CanFdFr04.h"
#include "DBC/SSMBMid6CanFdFr05.h"
#include "DBC/SSMBMid6CanFdFr06.h"
#include "DBC/SSMBMid6CanFdFr07.h"
#include "DBC/SSMBMid6CanFdFr08.h"
#include "DBC/SSMBMid6CanFdFr11.h"
#include "DBC/SSMMid3CanFr01.h"
#include "DBC/SSMMid3CanFr02.h"
#include "DBC/SSMMid3CanFr07.h"
#include "DBC/SSMMid3CanFr11.h"
#include "DBC/SSMMid5CanFdFr01.h"
#include "DBC/SSMMid5CanFdFr03.h"
#include "DBC/SSMMid5CanFdFr04.h"
#include "DBC/SSMMid5CanFdFr06.h"
#include "DBC/SSMMid5CanFdFr07.h"
#include "DBC/VCU1Mid3CanFr01.h"
#include "DBC/VCU1Mid3CanFr03.h"
#include "DBC/VCU1Mid3CanFr04.h"
#include "DBC/VCU1Mid3CanFr05.h"
#include "DBC/VCU1Mid3CanFr06.h"
#include "DBC/VCU1Mid3CanFr08.h"
#include "DBC/VCU1Mid3CanFr09.h"
#include "DBC/VCU1Mid3CanFr10.h"
#include "DBC/VCU1Mid3CanFr11.h"
#include "DBC/VCU1Mid3CanFr12.h"
#include "DBC/VCU1Mid3CanFr13.h"
#include "DBC/VCU1Mid3CanFr15.h"
#include "DBC/VCU1Mid3CanFr17.h"
#include "DBC/VCU1Mid3CanFr18.h"
#include "DBC/VCU1Mid3CanFr20.h"
#include "DBC/VCU1Mid3CanFr21.h"
#include "DBC/VCU1Mid3CanFr22.h"
#include "DBC/VCU1Mid3CanFr23.h"
#include "DBC/VCU1Mid3CanFr24.h"
#include "DBC/VCU1Mid3CanFr25.h"
#include "DBC/VCU1Mid3CanFr28.h"
#include "DBC/VCU1Mid3CanFr30.h"
#include "DBC/VCU1Mid3CanFr31.h"
#include "DBC/VCU1Mid3CanFr34.h"
#include "DBC/VCU1Mid3CanFr35.h"
#include "DBC/VCU1Mid3CanFr36.h"
#include "DBC/VIMBMid6CanFdFr01.h"
#include "DBC/VIMBMid6CanFdFr03.h"
#include "DBC/VIMBMid6CanFdFr04.h"
#include "DBC/VIMBMid6CanFdFr14.h"
#include "DBC/VIMBMid6CanFdFr19.h"
#include "DBC/VIMBMid6CanFdFr20.h"
#include "DBC/VIMBMid6CanFdFr21.h"
#include "DBC/VIMBMid6CanFdFr22.h"
#include "DBC/VIMBMid6CanFdFr23.h"
#include "DBC/VIMBMid6CanFdFr24.h"
#include "DBC/VIMBMid6CanFdFr25.h"
#include "DBC/VIMBMid6CanFdFr26.h"
#include "DBC/VIMBMid6CanFdFr27.h"
#include "DBC/VIMBMid6CanFdFr28.h"
#include "DBC/VIMBMid6CanFdFr29.h"
#include "DBC/VIMMid3CanFr01.h"
#include "DBC/VIMMid3CanFr02.h"
#include "DBC/VIMMid3CanFr03.h"
#include "DBC/VIMMid3CanFr04.h"
#include "DBC/VIMMid3CanFr05.h"
#include "DBC/VIMMid3CanFr06.h"
#include "DBC/VIMMid3CanFr07.h"
#include "DBC/VIMMid3CanFr08.h"
#include "DBC/VIMMid3CanFr09.h"
#include "DBC/VIMMid3CanFr10.h"
#include "DBC/VIMMid3CanFr11.h"
#include "DBC/VIMMid3CanFr12.h"
#include "DBC/VIMMid3CanFr13.h"
#include "DBC/VIMMid3CanFr14.h"
#include "DBC/VIMMid3CanFr15.h"
#include "DBC/VIMMid5CanFdFr02.h"
#include "DBC/VIMMid5CanFdFr03.h"
#include "DBC/VIMMid5CanFdFr04.h"
#include "DBC/VIMMid5CanFdFr05.h"
#include "DBC/VIMMid5CanFdFr06.h"
#include "DBC/VIMMid5CanFdFr07.h"
#include "DBC/VIMMid5CanFdFr08.h"
#include "DBC/VIMMid5CanFdFr09.h"
#include "DBC/VIMMid5CanFdFr10.h"
#include "DBC/VIMMid5CanFdFr11.h"
#include "DBC/VIMMid5CanFdFr12.h"
#include "DBC/VIMMid5CanFdFr13.h"
#include "DBC/VIMPrototypeMid5CanFdFr13.h"
#include "DBC/Vcu1ToAllFuncMid3DiagReqFrame.h"
#include "DBC/VimMid5CanFdTimeSynchFr.h"
#include "DBC/VimbMid6CanFdTimeSynchFr.h"


namespace kcan {
namespace dbc {

using std::string;


const string NoName{"NoName"};


} // namespace dbc
} // namespace kcan

#endif
